INSERT INTO usuarios (nome, email, senha, data_cadastro) VALUES ('Arrascaeta', 'maria-luizamachado@example.org', '#8SxsilMbF', '2024-06-11');
INSERT INTO usuarios (nome, email, senha, data_cadastro) VALUES ('Joãozinho', 'ibrito@example.net', '$4dtN3yzhq', '2024-12-28');
INSERT INTO usuarios (nome, email, senha, data_cadastro) VALUES ('Matheus Pereira', 'montenegrodante@example.org', 'J+N9An(K9v', '2024-07-29');
INSERT INTO usuarios (nome, email, senha, data_cadastro) VALUES ('Juan Pablo Sorín', 'melissa40@example.com', '5yyZ^Epp^8', '2025-06-28');
INSERT INTO usuarios (nome, email, senha, data_cadastro) VALUES ('Fábio', 'ida-paz@example.com', 'O%A6XFbdkG', '2025-07-02');
INSERT INTO usuarios (nome, email, senha, data_cadastro) VALUES ('Gabigol', 'heitornascimento@example.net', '6eV9VVbH!3', '2025-11-13');
INSERT INTO usuarios (nome, email, senha, data_cadastro) VALUES ('Arroyo', 'eduardo37@example.net', 'sdGY3XMu#d', '2024-02-17');
INSERT INTO usuarios (nome, email, senha, data_cadastro) VALUES ('Alex', 'juliada-cunha@example.org', '$Yn7F@xQ48', '2024-03-10');
INSERT INTO usuarios (nome, email, senha, data_cadastro) VALUES ('Arrascaeta', 'benicioaraujo@example.net', '4^9dQSxzpo', '2025-02-08');
INSERT INTO usuarios (nome, email, senha, data_cadastro) VALUES ('Fabrício Bruno', 'ana-julia02@example.org', '5yyCNLUD(c', '2024-07-17');
INSERT INTO usuarios (nome, email, senha, data_cadastro) VALUES ('Everton Ribeiro', 'maitemacedo@example.net', '&+7o^C3sa&', '2023-12-20');
INSERT INTO usuarios (nome, email, senha, data_cadastro) VALUES ('Lucas Romero', 'fariasisis@example.org', '3uORuMSc%E', '2024-11-16');
INSERT INTO usuarios (nome, email, senha, data_cadastro) VALUES ('Bolasie', 'kda-mota@example.net', 'i4F5Fqs$*0', '2025-04-08');
INSERT INTO usuarios (nome, email, senha, data_cadastro) VALUES ('Cássio', 'pintovalentim@example.net', '#4vgBXPckO', '2024-08-17');
INSERT INTO usuarios (nome, email, senha, data_cadastro) VALUES ('Kaio Jorge', 'maria-isis14@example.com', 'v$j2YJcFNL', '2024-06-25');
INSERT INTO usuarios (nome, email, senha, data_cadastro) VALUES ('Arroyo', 'fernando97@example.com', '!5T(_4Zlk9', '2023-12-09');
INSERT INTO usuarios (nome, email, senha, data_cadastro) VALUES ('Lucas Romero', 'correiaana-sophia@example.net', 't$m8eafG*I', '2024-08-18');
INSERT INTO usuarios (nome, email, senha, data_cadastro) VALUES ('Dedé', 'anthonygoncalves@example.org', 'pSFvZ@pJ$9', '2024-08-07');
INSERT INTO usuarios (nome, email, senha, data_cadastro) VALUES ('Marcelo Moreno', 'ymachado@example.org', '+^6GjQNre9', '2024-09-14');
INSERT INTO usuarios (nome, email, senha, data_cadastro) VALUES ('Bolasie', 'juliana54@example.com', '%0APcpNt)A', '2024-03-05');
INSERT INTO usuarios (nome, email, senha, data_cadastro) VALUES ('Juan Pablo Sorín', 'ooliveira@example.org', '0ABQrjoT%h', '2024-07-08');
INSERT INTO usuarios (nome, email, senha, data_cadastro) VALUES ('Sinisterra', 'brunosales@example.net', '(#J0G7Bbb@', '2024-10-10');
INSERT INTO usuarios (nome, email, senha, data_cadastro) VALUES ('Alex', 'agathateixeira@example.com', ')I^2WMve16', '2025-09-29');
INSERT INTO usuarios (nome, email, senha, data_cadastro) VALUES ('Gabigol', 'maria-claragomes@example.org', 'z#abD5@wUH', '2025-03-13');
INSERT INTO usuarios (nome, email, senha, data_cadastro) VALUES ('Bolasie', 'wrezende@example.org', 'J7BbE47s_m', '2024-05-17');
INSERT INTO usuarios (nome, email, senha, data_cadastro) VALUES ('Arrascaeta', 'eloa96@example.org', '_3%%Q2Im30', '2024-11-24');
INSERT INTO usuarios (nome, email, senha, data_cadastro) VALUES ('Arroyo', 'cnunes@example.net', ')37XK8Q67m', '2024-04-25');
INSERT INTO usuarios (nome, email, senha, data_cadastro) VALUES ('Dedé', 'sophiebarbosa@example.com', '$1Jj0H7BMn', '2024-04-15');
INSERT INTO usuarios (nome, email, senha, data_cadastro) VALUES ('Douglas Luiz', 'maitefreitas@example.com', '2dIZcrXt)F', '2025-08-09');
INSERT INTO usuarios (nome, email, senha, data_cadastro) VALUES ('Fábio', 'barbara16@example.net', 'lN0NEG8m)3', '2025-03-27');
INSERT INTO usuarios (nome, email, senha, data_cadastro) VALUES ('Fábio', 'bento76@example.com', 'AcI19rCf@)', '2025-03-16');
INSERT INTO usuarios (nome, email, senha, data_cadastro) VALUES ('Arrascaeta', 'elisalopes@example.org', 'm)W6W5uvdo', '2024-04-29');
INSERT INTO usuarios (nome, email, senha, data_cadastro) VALUES ('Juan Pablo Sorín', 'jesushenry@example.com', 'dRUNG6raD$', '2025-08-11');
INSERT INTO usuarios (nome, email, senha, data_cadastro) VALUES ('Cássio', 'xpacheco@example.com', '$0HkSx(eX+', '2025-02-25');
INSERT INTO usuarios (nome, email, senha, data_cadastro) VALUES ('Douglas Luiz', 'ana-liz20@example.net', '%!mJii*A2y', '2024-06-18');
INSERT INTO usuarios (nome, email, senha, data_cadastro) VALUES ('Sinisterra', 'luiz-otavio54@example.net', 'p^dS5H4tOT', '2024-12-10');
INSERT INTO usuarios (nome, email, senha, data_cadastro) VALUES ('Arroyo', 'limamateus@example.org', '#WKMzryK#5', '2024-12-25');
INSERT INTO usuarios (nome, email, senha, data_cadastro) VALUES ('Arrascaeta', 'jnovais@example.net', '@mv6Lvg3US', '2025-01-27');
INSERT INTO usuarios (nome, email, senha, data_cadastro) VALUES ('Cássio', 'kvargas@example.net', 'j1Z@5VEtNu', '2024-04-12');
INSERT INTO usuarios (nome, email, senha, data_cadastro) VALUES ('Alex', 'luiz-fernandofreitas@example.net', '&9+)N5Jn$W', '2024-10-30');
INSERT INTO usuarios (nome, email, senha, data_cadastro) VALUES ('Juan Pablo Sorín', 'svargas@example.com', '#VY$xKYv6A', '2025-03-28');
INSERT INTO usuarios (nome, email, senha, data_cadastro) VALUES ('Dedé', 'casa-grandeisabel@example.org', '@*1sOBRex9', '2025-11-05');
INSERT INTO usuarios (nome, email, senha, data_cadastro) VALUES ('Fabrício Bruno', 'trodrigues@example.org', 'r&&8SFcxc^', '2024-02-12');
INSERT INTO usuarios (nome, email, senha, data_cadastro) VALUES ('Kaio Jorge', 'isis86@example.net', '#K7$Wgyl(P', '2025-11-21');
INSERT INTO usuarios (nome, email, senha, data_cadastro) VALUES ('Juan Pablo Sorín', 'lleao@example.org', '*gQFma^ty3', '2024-08-06');
INSERT INTO usuarios (nome, email, senha, data_cadastro) VALUES ('Kaio Jorge', 'ferreirabryan@example.net', 'H_Q+8KmG@D', '2025-07-12');
INSERT INTO usuarios (nome, email, senha, data_cadastro) VALUES ('Marcelo Moreno', 'mouraarthur-miguel@example.net', '%OXANCxks5', '2024-04-30');
INSERT INTO usuarios (nome, email, senha, data_cadastro) VALUES ('Kaio Jorge', 'bernardosousa@example.org', '$4rZY^hVy8', '2024-07-18');
INSERT INTO usuarios (nome, email, senha, data_cadastro) VALUES ('Matheus Pereira', 'vasconceloscaue@example.com', '#n7jQBMu^L', '2024-10-22');
INSERT INTO usuarios (nome, email, senha, data_cadastro) VALUES ('Fábio', 'xlima@example.com', 'xnEFn2RrN(', '2024-02-18');